gazebo_ros_control:
  pid_gains:
    joint1:
      p: 5000.0
      i: 80.0
      d: 50.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    joint2:
      p: 5000.0
      i: 80.0
      d: 50.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    joint3:
      p: 5000.0
      i: 80.0
      d: 50.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    joint4:
      p: 5000.0
      i: 80.0
      d: 50.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    # gripper:
    #   p: 50.0
    #   i: 0.5
    #   d: 30.0
    #   i_clamp: 0.2
    #   antiwindup: false
    #   publish_state: true
    # gripper_sub:
    #   p: 50.0
    #   i: 0.5
    #   d: 30.0
    #   i_clamp: 0.2
    #   antiwindup: false
    #   publish_state: true

